baseURL         = "http://localhost"
title           = "tanis.codes"
languageCode    = "en-us"
paginate        = 10
enableGitInfo   = true

[params]
    env             = "local"

    dateform        = "Aug 7, 2022"
    dateformShort   = "Aug 7"
    dateformNum     = "2022-08-07"
    dateformNumTime = "2022-08-07 21:50"
    dateFormat      = "02 Jan 06 15:04 MST"

    [params.footer]
        author = "Estanislao Pérez Nartallo"
        copyright = true
        rss = true

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/pereznartallo/"
        weight = 30

    [[params.social]]
        name = "github"
        url = "https://github.com/tanisperez"
        weight = 30

    [[params.social]]
        name = "X"
        url = "https://x.com/TanisCodes"
        weight = 30

    [[params.social]]
        name = "rss"
        url = "/posts/index.xml"
        weight = 30

[languages]
    [languages.en]
        title = "tanis.codes"
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
        logoText = "tanis.codes"
        logoHomeLink = "/"

    [[menu.main]]
        identifier = "posts"
        name       = "Posts"
        url        = "/posts"