baseURL         = "https://tanis.codes"
title           = "tanis.codes"
languageCode    = "en-us"
enableGitInfo   = false

[outputs]
    home = ["HTML", "RSS", "JSON"]

[pagination]
    pagerSize = 10

[taxonomies]
    tag = "tags"

[params]
    env             = "pro"

    homeTitle       = "Articles about Backend, DevOps, Systems and Performance"
    description     = "Articles and tutorials about programming, clean code, patterns, command line, build tools, hardware and integrated systems"

    dateform        = "Aug 7, 2022"
    dateformShort   = "Aug 7"
    dateformNum     = "2022-08-07"
    dateformNumTime = "2022-08-07 21:50"
    dateFormat      = "02 Jan 06 15:04 MST"

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/pereznartallo/"
        weight = 30

    [[params.social]]
        name = "github"
        url = "https://github.com/tanisperez"
        weight = 30

    [[params.social]]
        name = "X"
        url = "https://x.com/TanisCodes"
        weight = 30

    [[params.social]]
        name = "rss"
        url = "/posts/index.xml"
        weight = 30

[languages]
    [languages.en]
        title = "tanis.codes"
        copyright = "Creative Commons CC BY-NC 4.0"

    [languages.en.params.author]
        name = "Estanislao Pérez Nartallo"

    [languages.en.params.logo]
        logoText = "tanis.codes"
        logoHomeLink = "https://tanis.codes"

    [[menu.main]]
        identifier = "posts"
        name       = "Posts"
        url        = "/posts"
